---
#### INVENTORY
- name: create workshop inventory
  awx.awx.tower_inventory:
    name: "Workshop Inventory"
    organization: "Default"
    controller_username: admin
    controller_password: "{{ admin_password }}"
    controller_host: "{{ ansible_host }}"
    validate_certs: false
  register: workshop_inventory
  until: workshop_inventory is success
  delay: 3
  retries: 5

- name: import inventory
  shell: 'tower-manage inventory_import --source=/home/{{ username }}/lab_inventory/hosts --inventory-name="Workshop Inventory"'
#### END OF INVENTORY

#### CREDENTIAL
- name: add SSH credential into Ansible Tower
  awx.awx.tower_credential:
    name: "Workshop Credential"
    inputs:
      username: ec2-user
      ssh_key_data: "{{ lookup('file', playbook_dir +'/' + ec2_name_prefix + '/' + ec2_name_prefix + '-private.pem') }}"
    credential_type: Machine
    organization: Default
    state: present
    controller_host: "{{ ansible_host }}"
    controller_username: admin
    controller_password: "{{ admin_password }}"
    validate_certs: false

- name: add tower credential into ansible tower
  awx.awx.tower_credential:
    name: "Tower Credential"
    inputs:
      username: admin
      password: "{{ admin_password }}"
    credential_type: Ansible Tower
    organization: Default
    state: present
    controller_host: "{{ ansible_host }}"
    controller_username: admin
    controller_password: "{{ admin_password }}"
    validate_certs: false

#### END OF CREDENTIAL

#### REMOVE BUILT-IN DEMO CONTENT
- name: delete demo job template
  awx.awx.tower_job_template:
    name: "Demo Job Template"
    state: absent
    controller_username: admin
    controller_password: "{{ admin_password }}"
    controller_host: "{{ ansible_host }}"
    validate_certs: false

- name: remove demo credential
  awx.awx.tower_credential:
    name: "Demo Credential"
    credential_type: Machine
    organization: Default
    state: absent
    controller_host: "{{ ansible_host }}"
    controller_username: admin
    controller_password: "{{ admin_password }}"
    validate_certs: false

- name: remove demo inventory
  awx.awx.tower_inventory:
    name: "Demo Inventory"
    organization: "Default"
    state: absent
    controller_username: admin
    controller_password: "{{ admin_password }}"
    controller_host: "{{ ansible_host }}"
    validate_certs: false

- name: remove built-in tower project
  awx.awx.tower_project:
    name: "Demo Project"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/ansible-tower-samples"
    state: absent
    controller_username: admin
    controller_password: "{{ admin_password }}"
    controller_host: "{{ ansible_host }}"
    validate_certs: false
#### END OF REMOVE BUILT-IN DEMO CONTENT

- name: setup workshop specific tower information
  include_tasks: "{{item}}"
  with_first_found:
    - "{{role_path}}/tasks/{{workshop_type}}.yml"
    - "{{role_path}}/tasks/unsupported_workshop.yml"
