---
# Import config
- name: Import all tower assets
  awx.awx.tower_import:
    controller_host: "{{ username }}.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
    controller_username: admin
    controller_password: "{{ admin_password }}"
    validate_certs: false
    assets: "{{ lookup('template', 'tower_config_sap.yml.j2') | from_yaml() }}"