---

## include workshop specific tasks for any cleanup
- name: include workshop specific tasks for any cleanup
  include_tasks: 'teardown_{{ workshop_type }}.yml'

- name: Get the VPC ID for {{ ec2_name_prefix }}
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ ec2_name_prefix }}-vpc"
    region: "{{ ec2_region }}"
  register: vpc_net_facts

- name: debug vpc_net_facts
  debug:
    var: vpc_net_facts
  when: debug_teardown


- name: debugging vpc id for {{ ec2_name_prefix }}
  debug:
    msg: "vpc id:'{{vpc_net_facts.vpcs[0].id}}'"
  when:
    - debug_teardown
    - vpc_net_facts.vpcs|length > 0

- name: use set fact for easier variables
  set_fact:
    ec2_vpc_id: "{{vpc_net_facts.vpcs[0].id|default('WORKSHOP_UNDEF')}}"
    ec2_security_group: "{{ ec2_name_prefix }}-insecure_all"
  when: ec2_security_group is undefined

- name: debug ec2_vpc_id
  debug:
    var: ec2_vpc_id
  when: debug_teardown

- name: debug ec2_security_group
  debug:
    var: ec2_security_group
  when: debug_teardown

- name: debug ec2_security_group2
  debug:
    var: ec2_security_group2
  when: debug_teardown

# retrieve instances for VPC 1
- name: grab vpc node facts for workshop
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      "vpc-id": "{{ec2_vpc_id}}"
  register: all_workshop_vpc_nodes

- name: debug all_workshop_vpc_nodes
  debug:
    var: all_workshop_vpc_nodes
  when: debug_teardown|bool

# Destroy VPC 1 instances
- name: destroy EC2 instances
  ec2:
    region: "{{ ec2_region }}"
    state: absent
    instance_ids: "{{ all_workshop_vpc_nodes.instances | map(attribute='instance_id') | list }}"
    wait: true
    wait_timeout: "{{ student_total * 300 | int}}"
  register: result_ec2_destroy
  when: all_workshop_vpc_nodes.instances

- name: debug result_ec2_destroy
  debug:
    var: result_ec2_destroy
  when: debug_teardown|bool

- name: Cleanup eni for {{ ec2_name_prefix }}-vpc (SECURITY MODE)
  block:
    - name: Get subnet1 eni_info
      ec2_eni_info:
        region: "{{ ec2_region }}"
        filters:
          "tag:Subnet": '{{ ec2_name_prefix }}-subnet1'
      register: dangling_eni_info

    - name: debug subnet1_eni_info
      debug:
        var: dangling_eni_info
      when: debug_teardown

    - name: Delete dangling ENIs from for {{ ec2_name_prefix }}-vpc
      ec2_eni:
        region: "{{ ec2_region }}"
        eni_id: "{{item['id']}}"
        state: absent
      loop: "{{dangling_eni_info['network_interfaces']}}"
  when: workshop_type == 'sap'

- name: Deleted EC2 security group for VPC vpc-{{ ec2_name_prefix }}
  ec2_group:
    name: "{{ec2_security_group}}"
    region: "{{ ec2_region }}"
    vpc_id: "{{ec2_vpc_id}}"
    state: absent
  register: delete_sg
  until: delete_sg is not failed
  retries: 50
  when: vpc_net_facts.vpcs|length > 0

# delete ec2_subnet for vpc-1
- name: Delete subnet for {{ ec2_name_prefix }}-vpc
  ec2_vpc_subnet:
    region: "{{ ec2_region }}"
    az: "{{ec2_az}}"
    vpc_id: "{{ec2_vpc_id}}"
    cidr: "{{ec2_subnet}}"
    state: absent

# delete ec2_subnet2 for vpc-1
- name: Delete subnet2 for {{ ec2_name_prefix }}-vpc
  ec2_vpc_subnet:
    region: "{{ ec2_region }}"
    az: "{{ec2_az}}"
    vpc_id: "{{ec2_vpc_id}}"
    cidr: "{{ec2_subnet2}}"
    state: absent

- name: vpc internet gateway is deleted for vpc-{{ ec2_name_prefix }}
  ec2_vpc_igw:
    region: "{{ ec2_region }}"
    vpc_id: "{{ec2_vpc_id}}"
    state: absent

- name: grab route information for {{ ec2_name_prefix }} on {{ ec2_region }}
  ec2_vpc_route_table_info:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ec2_vpc_id}}"
  register: route_table_facts

- name: vpc public subnet route table is deleted
  ec2_vpc_route_table:
    region: "{{ ec2_region }}"
    vpc_id: "{{ec2_vpc_id}}"
    route_table_id: "{{item.id}}"
    lookup: id
    state: absent
  with_items: "{{route_table_facts.route_tables}}"
  when: item.associations == []

- name: set keys for instance creation dynamically since key was not supplied by user
  set_fact:
    ec2_key_name: "{{ ec2_name_prefix }}-key"

- name: delete ssh key pair for workshop {{ ec2_name_prefix }}
  ec2_key:
    name: "{{ec2_key_name}}"
    region: "{{ ec2_region }}"
    state: absent

- name: delete s3 bucket for persistent storage of ec2 key
  s3_bucket:
    name: "{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone|lower }}.private"
    state: absent
    region: "{{ ec2_region }}"
    force: true
  retries: 4
  delay: 15
  register: s3_result
  until:
    - s3_result.failed == false

# delete VPCS
- name: delete AWS VPC {{ ec2_name_prefix }}
  ec2_vpc_net:
    name: "{{ ec2_name_prefix }}-vpc"
    cidr_block: "{{ ec2_subnet }}"
    region: "{{ ec2_region }}"
    state: absent
